import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
  index("routes/home.tsx"),
  route("login", "routes/login.tsx"),
  route("signup", "routes/signup.tsx"),
  route("logout", "routes/logout.tsx"),
  route("dashboard", "routes/dashboard.tsx"),
  route("admin", "routes/admin.tsx"),
  route("bulk-operations", "routes/bulk-operations.tsx"),
  route("api/bulk-operations", "routes/api.bulk-operations.tsx"),
  route("shipment-plans", "routes/shipment-plans.tsx"),
  route("shipment-plans/new", "routes/shipment-plans.new.tsx"),
  route("shipment-plans/:id/edit", "routes/shipment-plans.$id.edit.tsx"),
  route("api/shipment-plans", "routes/api.shipment-plans.tsx"),
  route("liner-bookings", "routes/liner-bookings.tsx"),
  route("liner-bookings/new", "routes/liner-bookings.new.tsx"),
  route("liner-bookings/:id/edit", "routes/liner-bookings.$id.edit.tsx"),
  route("api/liner-bookings", "routes/api.liner-bookings.tsx"),
  
  // Data Points Routes
  route("data-points/organizations", "routes/data-points.organizations.tsx"),
  route("data-points/organizations/new", "routes/data-points.organizations.new.tsx"),
  route("data-points/organizations/:id/edit", "routes/data-points.organizations.$id.edit.tsx"),
  route("data-points/business-branches", "routes/data-points.business-branches.tsx"),
  route("data-points/business-branches/new", "routes/data-points.business-branches.new.tsx"),
  route("data-points/business-branches/:id/edit", "routes/data-points.business-branches.$id.edit.tsx"),
  route("data-points/commodities", "routes/data-points.commodities.tsx"),
  route("data-points/commodities/new", "routes/data-points.commodities.new.tsx"),
  route("data-points/commodities/:id/edit", "routes/data-points.commodities.$id.edit.tsx"),
  route("data-points/equipment", "routes/data-points.equipment.tsx"),
  route("data-points/equipment/new", "routes/data-points.equipment.new.tsx"),
  route("data-points/equipment/:id/edit", "routes/data-points.equipment.$id.edit.tsx"),
  route("data-points/loading-ports", "routes/data-points.loading-ports.tsx"),
  route("data-points/loading-ports/new", "routes/data-points.loading-ports.new.tsx"),
  route("data-points/loading-ports/:id/edit", "routes/data-points.loading-ports.$id.edit.tsx"),
  route("data-points/ports-of-discharge", "routes/data-points.ports-of-discharge.tsx"),
  route("data-points/ports-of-discharge/new", "routes/data-points.ports-of-discharge.new.tsx"),
  route("data-points/ports-of-discharge/:id/edit", "routes/data-points.ports-of-discharge.$id.edit.tsx"),
  route("data-points/destination-countries", "routes/data-points.destination-countries.tsx"),
  route("data-points/destination-countries/new", "routes/data-points.destination-countries.new.tsx"),
  route("data-points/destination-countries/:id/edit", "routes/data-points.destination-countries.$id.edit.tsx"),
  route("data-points/vessels", "routes/data-points.vessels.tsx"),
  route("data-points/vessels/new", "routes/data-points.vessels.new.tsx"),
  route("data-points/vessels/:id/edit", "routes/data-points.vessels.$id.edit.tsx"),
  route("data-points/carriers", "routes/data-points.carriers.tsx"),
  route("data-points/carriers/new", "routes/data-points.carriers.new.tsx"),
  route("data-points/carriers/:id/edit", "routes/data-points.carriers.$id.edit.tsx"),
] satisfies RouteConfig;
